# Generated by Django 5.0.6 on 2024-06-26 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='apartment',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='city',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='house',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='id',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='street',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
