# Generated by Django 5.0.6 on 2024-06-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='postal_code',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='street_address',
            field=models.CharField(default=1, help_text='The combination of the street name, house number and apartment', max_length=150),
            preserve_default=False,
        ),
    ]
