# Generated by Django 5.0.6 on 2024-06-26 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_shippingaddress_apartment_shippingaddress_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='longitude',
            new_name='longtitude',
        ),
    ]
